export const LESSON_CONTENT = {
  1: {
    intro: { guidance: "This lesson introduces the concept of literature itself. Read a short overview of literary forms before taking the quiz — the Khan Academy reading foundation page is a great start.", source: "Khan Academy — Introduction to Literary Text", sourceUrl: "https://www.khanacademy.org/humanities/grammar/reading-and-writing-foundation", readingTime: "~10 minutes" },
    slides: [
      { title: "What is Literature?", text: "Literature is written work considered to have artistic merit. It encompasses novels, short stories, poetry, plays, and essays. What separates literature from other writing is its depth — it invites readers to think, feel, and question the human experience." },
      { title: "The Three Forms", text: "The three main forms are prose (novels, short stories), poetry (verse, sonnets, ballads), and drama (plays, screenplays). Each form uses language differently to create meaning and emotional impact." },
      { title: "Why Literature Matters", text: "Literature is a mirror of the human experience. Through stories and poems, we explore emotions and situations we may never encounter in our own lives. It builds empathy, expands perspective, and preserves cultural memory across generations." },
    ],
    questions: [
      { type: "comprehension", text: "Which of the following is NOT typically considered literature?", options: ["A poem about nature", "A novel about war", "A grocery list", "A play about love"], correct_index: 2, explanation: "Literature has artistic intent and merit. A grocery list is purely functional writing with no artistic purpose." },
      { type: "comprehension", text: "What primarily separates literature from other forms of writing?", options: ["Its length", "Its artistic depth and intent", "Its publication date", "The author's nationality"], correct_index: 1, explanation: "Literature is distinguished by its artistic merit and depth — it invites readers to think, feel, and question." },
      { type: "vocabulary", text: "What does 'prose' mean in the context of literature?", options: ["Writing structured in verse and meter", "Ordinary written or spoken language", "A dramatic monologue", "A type of ancient epic poem"], correct_index: 1, explanation: "Prose is ordinary written language — it includes novels, short stories, and essays, as distinct from poetry." },
      { type: "comprehension", text: "According to the lesson, what is one key purpose of literature?", options: ["To record historical facts", "To teach grammar", "To build empathy and expand perspective", "To entertain only"], correct_index: 2, explanation: "Literature builds empathy by letting us experience lives and emotions beyond our own direct experience." },
    ],
  },
  2: {
    intro: { guidance: "Every story is built from core elements. To prepare, read 'The Most Dangerous Game' by Richard Connell — a short story that perfectly demonstrates all five story elements in action.", source: "Richard Connell — The Most Dangerous Game (1924)", sourceUrl: "https://www.gutenberg.org/files/12032/12032-h/12032-h.htm", readingTime: "~45 minutes" },
    slides: [
      { title: "Character & Setting", text: "Characters are the people who inhabit the story. The protagonist drives the story forward; the antagonist creates opposition. Setting is where and when the story takes place — it shapes mood, conflict, and character. In 'The Most Dangerous Game,' the isolated island setting is inseparable from the story's dread." },
      { title: "Plot & Conflict", text: "Plot is the sequence of events: exposition, rising action, climax, falling action, and resolution. At the heart of plot is conflict — man vs. man, man vs. nature, man vs. self, or man vs. society. The climax is the moment of highest tension." },
      { title: "Theme", text: "Theme is the central idea or message of a story. It's not just a topic ('hunting') but a statement about the human condition ('When humans become the hunted, we confront the ethics of predator and prey'). Great stories contain multiple interwoven themes." },
    ],
    questions: [
      { type: "comprehension", text: "In 'The Most Dangerous Game', the central conflict is best described as:", options: ["Man vs. nature (surviving a shipwreck)", "Man vs. man (being hunted by General Zaroff)", "Man vs. self (overcoming fear)", "Man vs. society (escaping civilization)"], correct_index: 1, explanation: "The central conflict is man vs. man — Rainsford is hunted by General Zaroff across the island." },
      { type: "comprehension", text: "Which part of the plot arc is the CLIMAX?", options: ["When the main character is introduced", "When background information is given", "When the final conflict reaches its peak tension", "When the story ends peacefully"], correct_index: 2, explanation: "The climax is the turning point of greatest tension — the peak of rising action before the resolution begins." },
      { type: "vocabulary", text: "What does 'protagonist' mean?", options: ["The main villain of a story", "The narrator who tells the story", "The central character who drives the action", "A minor character who helps the hero"], correct_index: 2, explanation: "The protagonist is the main character whose journey or conflict we follow throughout the story." },
      { type: "comprehension", text: "What is the THEME of a story?", options: ["A summary of what happens", "The location where events take place", "A central message or idea about human experience", "The genre of the book"], correct_index: 2, explanation: "Theme is the underlying message or insight about life that the story communicates, beyond just the plot events." },
    ],
  },
  3: {
    intro: { guidance: "Read Dylan Thomas's 'Do Not Go Gentle into That Good Night' and Robert Frost's 'The Road Not Taken'. Both are short but packed with poetic technique. Read them aloud — poetry is meant to be heard.", source: "Dylan Thomas — Do Not Go Gentle into That Good Night (1951)", sourceUrl: "https://poets.org/poem/do-not-go-gentle-good-night", readingTime: "~15 minutes" },
    slides: [
      { title: "Do Not Go Gentle into That Good Night", text: "Do not go gentle into that good night,\nOld age should burn and rave at close of day;\nRage, rage against the dying of the light.\n\nThough wise men at their end know dark is right,\nBecause their words had forked no lightning they\nDo not go gentle into that good night.\n\n— Dylan Thomas, 1951", isPoem: true },
      { title: "Rhythm & Meter", text: "Meter is the rhythmic pattern of stressed and unstressed syllables in a line of poetry. The most common in English is iambic pentameter — five 'iambs' per line (da-DUM da-DUM da-DUM da-DUM da-DUM). Shakespeare's sonnets and much of Thomas's work use this form." },
      { title: "The Villanelle Form", text: "Thomas's poem is a villanelle — a 19-line poem with two repeating refrain lines. The form creates an obsessive, circular quality that mirrors the speaker's desperate plea. The strict structure contrasts powerfully with the raw emotion of the content." },
    ],
    questions: [
      { type: "comprehension", text: "In 'Do Not Go Gentle', what does the speaker urge his father to do?", options: ["Accept death with peace and grace", "Rage and fight against death", "Write poetry about aging", "Travel while there is still time"], correct_index: 1, explanation: "The repeated refrain 'Rage, rage against the dying of the light' urges his father to resist death with fierce spirit." },
      { type: "comprehension", text: "What poetic form is 'Do Not Go Gentle into That Good Night'?", options: ["A sonnet", "A haiku", "A villanelle", "A ballad"], correct_index: 2, explanation: "It is a villanelle — a 19-line poem with two refrains that repeat throughout the poem." },
      { type: "vocabulary", text: "What is 'meter' in poetry?", options: ["The length of the poem in lines", "A rhythmic pattern of stressed and unstressed syllables", "The poem's central theme", "The number of verses or stanzas"], correct_index: 1, explanation: "Meter is the rhythmic pattern created by stressed and unstressed syllables — it gives poetry its musical quality." },
      { type: "vocabulary", text: "What does 'refrain' mean in poetry?", options: ["A type of rhyme scheme", "A line or stanza that repeats throughout a poem", "The final verse of a poem", "The title of a poem"], correct_index: 1, explanation: "A refrain is a line or phrase that repeats at intervals — creating emphasis and emotional intensity." },
    ],
  },
  4: {
    intro: { guidance: "Read Book 9 of Homer's Odyssey — the Cyclops episode. It's one of the most gripping episodes in ancient literature and introduces key epic conventions.", source: "Homer — The Odyssey, Book 9 (c. 800 BCE)", sourceUrl: "https://www.gutenberg.org/cache/epub/1727/pg1727-images.html", readingTime: "~30 minutes" },
    slides: [
      { title: "The Cyclops Episode", text: "\"We reached the land of the Cyclops race,\nArrogant folk who trust the gods so much\nThey never plant or plow, yet all things grow...\nWe found the cave. Inside were lambs and kids\nAll sorted into pens by age, and cheese\nFilled every rack; the pails were full of whey.\"\n\n— Homer, The Odyssey, Book 9", isPoem: true },
      { title: "What is an Epic?", text: "An epic is a long narrative poem about a hero's grand journey. The Odyssey follows Odysseus as he struggles to return home after the Trojan War. Epic conventions include: invocation of a muse, beginning in medias res (in the middle of action), and a hero tested by gods and monsters." },
      { title: "Hubris — The Fatal Flaw", text: "A key theme in Greek myth is hubris — excessive pride that leads to downfall. After blinding the Cyclops Polyphemus, Odysseus shouts his real name in triumph. This allows Polyphemus to call down his father Poseidon's wrath — a perfect example of how pride undoes even the cleverest hero." },
    ],
    questions: [
      { type: "comprehension", text: "Why does Odysseus revealing his name to the Cyclops cause lasting problems?", options: ["It angers Zeus directly", "It allows Polyphemus to invoke Poseidon's curse against him", "It breaks a sacred oath to the gods", "It tells the Cyclops where his home island is"], correct_index: 1, explanation: "By revealing his name, Odysseus enables Polyphemus to call upon his father Poseidon — demonstrating how hubris leads to consequences." },
      { type: "comprehension", text: "What does 'in medias res' mean as a storytelling technique?", options: ["Starting from the very beginning of events", "Starting in the middle of the action", "Starting with the hero's death", "Starting with a divine prophecy"], correct_index: 1, explanation: "'In medias res' is Latin for 'in the middle of things.' The Odyssey begins with Odysseus already stranded." },
      { type: "vocabulary", text: "What does 'hubris' mean?", options: ["Extreme cowardice in battle", "Excessive pride that leads to downfall", "Devotion to the gods", "Wisdom gained through suffering"], correct_index: 1, explanation: "Hubris is excessive pride or arrogance — a central flaw in Greek tragedy and myth that leads characters to their ruin." },
      { type: "vocabulary", text: "What is an 'epic' in literature?", options: ["A short lyric poem about love", "A long narrative poem about a hero's grand journey", "A comic play in five acts", "A philosophical dialogue"], correct_index: 1, explanation: "An epic is a long narrative poem telling the tale of a hero's extraordinary journey, often involving gods and monsters." },
    ],
  },
  5: {
    intro: { guidance: "Read Shakespeare's Sonnet 18 ('Shall I compare thee to a summer's day?') — just 14 lines but extraordinarily rich. Also read Sonnet 73 if you have time.", source: "William Shakespeare — Sonnet 18 (c. 1600)", sourceUrl: "https://www.poetryfoundation.org/poems/45087/sonnet-18-shall-i-compare-thee-to-a-summers-day", readingTime: "~10 minutes" },
    slides: [
      { title: "Sonnet 18", text: "Shall I compare thee to a summer's day?\nThou art more lovely and more temperate:\nRough winds do shake the darling buds of May,\nAnd summer's lease hath all too short a date...\n\nBut thy eternal summer shall not fade,\nSo long as men can breathe or eyes can see,\nSo long lives this, and this gives life to thee.\n\n— William Shakespeare, c. 1600", isPoem: true },
      { title: "The Sonnet Form", text: "A Shakespearean sonnet has 14 lines in iambic pentameter, divided into three quatrains (4-line stanzas) and a closing couplet (2 lines). The volta — a turn in argument — typically occurs at line 9 or in the final couplet, where the poem's logic shifts." },
      { title: "Shakespeare's Argument", text: "Shakespeare argues that his beloved is more beautiful than summer — but summer fades. Poetry, however, is eternal. By writing about the beloved, Shakespeare grants them immortality. This was a radical claim: the poet's craft could defeat time itself." },
    ],
    questions: [
      { type: "comprehension", text: "To what does Shakespeare compare his beloved in Sonnet 18?", options: ["A winter's night", "A summer's day", "A spring morning", "An autumn harvest"], correct_index: 1, explanation: "The sonnet opens: 'Shall I compare thee to a summer's day?' — but argues the beloved is actually superior to summer." },
      { type: "comprehension", text: "What does Shakespeare claim will preserve his beloved's beauty forever?", options: ["A portrait painting", "A wedding vow", "This poem itself", "His own memory"], correct_index: 2, explanation: "The closing couplet: 'So long lives this, and this gives life to thee.' The poem grants immortality." },
      { type: "vocabulary", text: "What does 'temperate' mean in Sonnet 18?", options: ["Extremely passionate", "Mild and moderate in nature", "Cold and reserved", "Stormy and unpredictable"], correct_index: 1, explanation: "'Temperate' means mild and moderate. The beloved is 'more temperate' than summer — more balanced." },
      { type: "comprehension", text: "What is the 'volta' in a sonnet?", options: ["The opening image of the poem", "A turn or shift in the poem's argument", "The rhyming couplet at the end", "The meter pattern throughout"], correct_index: 1, explanation: "The volta is a rhetorical turn — a shift in argument or perspective that changes the poem's direction." },
    ],
  },
  6: {
    intro: { guidance: "Pick up any poem or literary novel and look for metaphor, simile, and personification. Langston Hughes's 'A Dream Deferred' is a brilliant, compact example to start with.", source: "Langston Hughes — A Dream Deferred (1951)", sourceUrl: "https://www.poetryfoundation.org/poems/46548/a-dream-deferred", readingTime: "~20 minutes" },
    slides: [
      { title: "A Dream Deferred", text: "What happens to a dream deferred?\nDoes it dry up\nlike a raisin in the sun?\nOr fester like a sore —\nAnd then run?\n...\nOr does it explode?\n\n— Langston Hughes, 1951", isPoem: true },
      { title: "Metaphor vs. Simile", text: "A simile compares two things using 'like' or 'as' ('Her voice was like honey'). A metaphor makes the comparison directly ('Her voice was honey'). Metaphors create stronger, more immediate images. Hughes uses similes throughout: 'Does it dry up / like a raisin in the sun?'" },
      { title: "Personification & Symbolism", text: "Personification gives human qualities to non-human things. Symbolism uses objects to represent larger ideas. In 'A Dream Deferred,' the deferred dream becomes a symbol for the delayed rights and hopes of Black Americans under systemic oppression." },
    ],
    questions: [
      { type: "comprehension", text: "'Life is a journey' is an example of which literary device?", options: ["Simile", "Metaphor", "Personification", "Alliteration"], correct_index: 1, explanation: "It's a metaphor — a direct comparison without using 'like' or 'as.' A simile would say 'Life is like a journey.'" },
      { type: "comprehension", text: "Which sentence uses a SIMILE?", options: ["The stars danced in the sky", "Her eyes were two bright stars", "He ran as fast as a cheetah", "The city never sleeps"], correct_index: 2, explanation: "'As fast as a cheetah' uses 'as' to make the comparison — that's a simile." },
      { type: "vocabulary", text: "What is 'personification'?", options: ["Comparing two things using 'like' or 'as'", "Giving human qualities to non-human things", "Repeating consonant sounds for effect", "Exaggerating to make a point"], correct_index: 1, explanation: "Personification attributes human traits to animals, objects, or ideas." },
      { type: "comprehension", text: "In 'A Dream Deferred', what does the deferred dream most likely symbolize?", options: ["A personal romantic disappointment", "The delayed hopes of Black Americans under oppression", "A child's lost toy", "The fear of death"], correct_index: 1, explanation: "Written in 1951, Hughes's poem speaks to the deferred dreams of Black Americans systematically denied opportunity." },
    ],
  },
  7: {
    intro: { guidance: "Read Wordsworth's 'I Wandered Lonely as a Cloud' and Keats's 'Ode to a Nightingale'. Both represent Romanticism at its most characteristic.", source: "William Wordsworth — I Wandered Lonely as a Cloud (1807)", sourceUrl: "https://www.poetryfoundation.org/poems/45521/i-wandered-lonely-as-a-cloud", readingTime: "~20 minutes" },
    slides: [
      { title: "I Wandered Lonely as a Cloud", text: "I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze.\n\n— William Wordsworth, 1807", isPoem: true },
      { title: "Romanticism: Core Ideas", text: "The Romantic movement (c. 1780–1850) celebrated nature, individual emotion, and imagination over reason and industry. Romantic poets believed nature was the source of spiritual truth. They wrote against the cold rationalism of the Enlightenment and the dehumanizing effects of the Industrial Revolution." },
      { title: "The Sublime", text: "The 'sublime' is a key Romantic concept — the awe-inspiring feeling produced by encountering vast, overwhelming nature. Unlike mere beauty, the sublime mixes wonder with a sense of one's own smallness before something much greater." },
    ],
    questions: [
      { type: "comprehension", text: "What does the speaker encounter in Wordsworth's poem?", options: ["A stormy sea at sunset", "A field of golden daffodils", "A mountain covered in snow", "A flock of migrating birds"], correct_index: 1, explanation: "The poem's central image is 'a host of golden daffodils' beside a lake." },
      { type: "comprehension", text: "What did Romantic poets believe was the highest source of truth and inspiration?", options: ["Scientific reason and logic", "Religious scripture alone", "Nature and individual emotion", "Classical Greek and Roman models"], correct_index: 2, explanation: "Romantics placed nature and feeling above reason. They saw the natural world as a source of spiritual insight." },
      { type: "vocabulary", text: "What does 'the sublime' mean in Romantic literature?", options: ["Something delicate and beautiful", "An awe-inspiring experience that overwhelms the senses, especially in nature", "A type of formal verse structure", "The moral lesson of a poem"], correct_index: 1, explanation: "The sublime is the overwhelming feeling produced by vast natural experiences." },
      { type: "comprehension", text: "Which movement did Romanticism primarily react against?", options: ["The Renaissance", "The Enlightenment and Industrial Revolution", "The Medieval period", "Ancient Greek philosophy"], correct_index: 1, explanation: "Romanticism was a reaction to Enlightenment rationalism and the effects of the Industrial Revolution." },
    ],
  },
  8: {
    intro: { guidance: "Read the opening chapters of 'The Catcher in the Rye' by J.D. Salinger — a masterclass in first-person unreliable narration. Pay close attention to how Holden's voice shapes everything.", source: "J.D. Salinger — The Catcher in the Rye (1951)", sourceUrl: "https://en.wikipedia.org/wiki/The_Catcher_in_the_Rye", readingTime: "~30 minutes" },
    slides: [
      { title: "Points of View", text: "First person ('I') — the narrator is a character; intimate but limited.\nSecond person ('you') — rare; draws the reader in directly.\nThird person limited ('he/she') — follows one character's perspective.\nThird person omniscient — all-knowing; access to all characters' thoughts." },
      { title: "The Unreliable Narrator", text: "An unreliable narrator cannot be fully trusted. Their account is biased, distorted, or incomplete — due to mental state, self-interest, or limited knowledge. Holden Caulfield constantly dismisses people as 'phony' — but his own cynicism distorts our view of events." },
      { title: "Voice as Meaning", text: "\"If you really want to hear about it, the first thing you'll probably want to know is where I was born, and what my lousy childhood was like...\"\n— Holden Caulfield\n\nHolden's colloquial, defensive voice IS the story. The narrator's personality shapes meaning as much as the events themselves.", isPoem: true },
    ],
    questions: [
      { type: "comprehension", text: "In first-person narration, what is a key LIMITATION?", options: ["The narrator knows too much", "The narrator can only share their own perspective", "The reader never learns the narrator's name", "Events must be told in strict chronological order"], correct_index: 1, explanation: "First-person narrators are limited to their own experience — they can't know what other characters think or feel." },
      { type: "comprehension", text: "An 'unreliable narrator' is best described as:", options: ["A narrator who writes very long sentences", "A narrator whose account cannot be fully trusted due to bias", "A narrator who speaks directly to the reader", "A narrator who only describes external physical events"], correct_index: 1, explanation: "Unreliable narrators are biased, self-deceived, or limited — readers must read between the lines." },
      { type: "vocabulary", text: "What does 'omniscient' mean in 'third-person omniscient' narration?", options: ["The narrator describes only external events", "The narrator has all-knowing access to all characters' thoughts", "The narrator is one of the story's characters", "The narrator speaks in second person"], correct_index: 1, explanation: "'Omniscient' means all-knowing. This narrator can access any character's thoughts and motivations." },
      { type: "comprehension", text: "Holden frequently calling people 'phony' suggests:", options: ["He is an objective and reliable observer", "His judgments reveal his own cynicism and biases more than reality", "He has special insight into human nature", "He is describing a factual societal problem"], correct_index: 1, explanation: "Holden's repeated use of 'phony' reveals his own biases and mental state — a classic sign of unreliable narration." },
    ],
  },
  9: {
    intro: { guidance: "Read the opening chapter of Kafka's 'The Metamorphosis' — just the first chapter is transformative. Then read Hemingway's 'Hills Like White Elephants' for a stark contrast in style.", source: "Franz Kafka — The Metamorphosis (1915)", sourceUrl: "https://www.gutenberg.org/files/5200/5200-h/5200-h.htm", readingTime: "~45 minutes" },
    slides: [
      { title: "The Metamorphosis — Opening", text: "\"As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect.\"\n\n— Franz Kafka, 1915", isPoem: true },
      { title: "Modernism & Alienation", text: "Modern fiction (roughly 1890–1940) explored the psychological interior of characters. Key themes: alienation, identity, the meaninglessness of modern bureaucracy. Kafka's Gregor turns into a bug — but the real horror is how his family treats him afterward, not the transformation itself." },
      { title: "Absurdism", text: "Absurdism (Camus, Kafka) holds that humans seek meaning in a universe that offers none. Characters are caught in inexplicable situations. Kafka's prose is deadpan as it describes the impossible — making the monstrous feel banal, and the banal feel monstrous." },
    ],
    questions: [
      { type: "comprehension", text: "What has happened to Gregor Samsa at the opening of 'The Metamorphosis'?", options: ["He has lost his job", "He has transformed into a giant insect", "He has won an unexpected inheritance", "He has had an extremely vivid dream"], correct_index: 1, explanation: "Kafka's opening line immediately states the transformation: 'he found himself transformed in his bed into a gigantic insect.'" },
      { type: "comprehension", text: "What is the TRUE horror in 'The Metamorphosis' according to literary analysis?", options: ["The physical appearance of the insect", "The way his family gradually abandons and neglects him", "The mystery of how the transformation occurred", "Gregor's inability to communicate"], correct_index: 1, explanation: "The real horror is not the physical transformation but how his family ultimately rejects and lets him die." },
      { type: "vocabulary", text: "What does 'absurdism' mean in a literary context?", options: ["A focus on realistic everyday domestic life", "The idea that life is inherently meaningless and humans futilely seek meaning", "A comedic style using exaggeration", "A narrative technique using extended flashbacks"], correct_index: 1, explanation: "Absurdism holds that the universe has no inherent meaning, and human attempts to find meaning are both tragic and darkly comic." },
      { type: "vocabulary", text: "What is 'stream of consciousness' in modern fiction?", options: ["A plot that follows events chronologically", "A narrative technique that mimics the continuous flow of a character's thoughts", "A story told from multiple perspectives", "A form of dialogue without quotation marks"], correct_index: 1, explanation: "Stream of consciousness tries to capture the unfiltered flow of a character's thoughts — used by Joyce, Woolf, and Faulkner." },
    ],
  },
  10: {
    intro: { guidance: "Read the opening pages of 'One Hundred Years of Solitude' by Gabriel García Márquez. Also watch Chimamanda Ngozi Adichie's TED talk 'The Danger of a Single Story'.", source: "Gabriel García Márquez — One Hundred Years of Solitude (1967)", sourceUrl: "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude", readingTime: "~30 minutes" },
    slides: [
      { title: "One Hundred Years of Solitude", text: "\"Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice.\"\n\n— Gabriel García Márquez, 1967\n\nThis single sentence encompasses past, present, and future — time collapses into a single moment of memory.", isPoem: true },
      { title: "Magic Realism", text: "Magic realism weaves magical or fantastical elements into otherwise realistic settings — treating the extraordinary as ordinary. Associated with Latin American literature (Márquez, Borges, Allende), it reflects oral tradition and a worldview where the spiritual and material are not separate realms." },
      { title: "The Danger of a Single Story", text: "Nigerian author Chimamanda Ngozi Adichie argues that when we only read literature from one tradition, we miss the full range of human experience. World literature expands our understanding of what it means to be human." },
    ],
    questions: [
      { type: "comprehension", text: "What narrative technique does the famous opening sentence of 'One Hundred Years of Solitude' use?", options: ["Strict chronological storytelling", "Collapsing past, present, and future in a single sentence", "Starting with a detailed setting description", "Beginning with dialogue between characters"], correct_index: 1, explanation: "The opening sentence jumps forward to the future while looking back at a past memory — time is fluid, not linear." },
      { type: "comprehension", text: "What distinguishes 'magic realism' from pure fantasy?", options: ["Magic realism is set in space", "Magic realism places fantastical events in realistic settings, treating them as ordinary", "Magic realism only uses ancient myths", "Magic realism has no human characters"], correct_index: 1, explanation: "In magic realism, the magical coexists with the everyday without surprise — it reflects a worldview where the spiritual and material are intertwined." },
      { type: "vocabulary", text: "What does 'diaspora' refer to in the context of world literature?", options: ["A narrative structure used in epics", "The spread of a people from their homeland, often explored through literature of displacement", "A poetic form originating in West Africa", "A literary prize awarded to global authors"], correct_index: 1, explanation: "Diaspora literature explores the experiences of people displaced from their homeland — themes of belonging and identity are central." },
      { type: "comprehension", text: "According to Adichie, what is the risk of only reading literature from one tradition?", options: ["It improves depth of knowledge in that tradition", "It leads to an incomplete and potentially harmful understanding of other peoples", "It makes you a more focused writer", "It has no real impact on perspective"], correct_index: 1, explanation: "Adichie argues that single-story narratives flatten cultures — world literature counters this by offering diverse, complex perspectives." },
    ],
  },
};
